
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024 
   config.vm.box = "ubuntu/trusty64" 
end
   config.vm.synced_folder "../data", "/vagrant/data"
   config.vm.network "forwarded_port", guest: 80, host: 8080
   config.vm.network "forwarded_port", guest: 5000, host: 5000
   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
	 suro apt-get install curl
	 sudo apt-get 
	 sudo curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
	 sudo apt-get install -y nodejs

     
   SHELL
end
